import Link from "next/link";
import { Cookie, FileText, Scale, ShieldCheck } from "lucide-react";

import { DiscoveryFooter } from "@/components/discovery/DiscoveryFooter";

import styles from "./BusinessPages.module.css";

type LegalKind = "privacy" | "terms" | "cookies";
type LegalSection = { id: string; title: string; paragraphs: readonly string[]; bullets?: readonly string[] };

const privacySections: readonly LegalSection[] = [
  { id: "overview", title: "1. Overview", paragraphs: ["This policy explains how the current ToolsApp implementation handles information. ToolsApp is temporary product naming; no separate legal entity, office, or jurisdiction is represented here.", "The service is primarily browser-local. Some optional features, especially AI generation, require server and third-party processing as described below."] },
  { id: "account", title: "2. Account and profile information", paragraphs: ["Production authentication is not currently connected. The Settings page can store an optional display name and contact email in this browser only; that local profile does not create an online account.", "Development builds may use a deterministic mock authentication service for interface testing. It is not a persistent production identity system."] },
  { id: "local-storage", title: "3. Browser-local storage", paragraphs: ["ToolsApp uses browser local storage for favorites, recent tool activity, recent searches, notification state, and local workspace preferences."], bullets: ["History contains tool identifiers, timestamps, source, and opened/completed status—not full file contents, text, JSON, AI briefs, or generated scripts.", "You can clear favorites and history from Settings or remove site data through your browser.", "Browser storage remains until you clear it, the app overwrites it, or the browser removes it."] },
  { id: "files", title: "4. File and text processing", paragraphs: ["The implemented image, PDF, text, JSON, and QR workflows run in the browser. Selected files and generated outputs are kept in browser memory while needed and are not uploaded to a ToolsApp storage service.", "Downloaded results are created through temporary browser object URLs that the app revokes after use. Closing or refreshing the page can discard unsaved in-memory work."] },
  { id: "ai", title: "5. AI prompt and provider processing", paragraphs: ["If live AI generation is configured and you submit a UGC brief, the browser sends the validated fields to the ToolsApp server endpoint. The server builds the provider prompt and sends it to the configured OpenAI Responses API.", "The provider request sets storage off, and ToolsApp does not intentionally log full prompts or place them in generic history. OpenAI still processes the submitted content to produce the response; its own service terms and data practices apply.", "Do not submit secrets, highly sensitive personal information, or content you are not authorized to process."] },
  { id: "cookies", title: "6. Cookies and similar technologies", paragraphs: ["ToolsApp does not currently include advertising or analytics trackers. When the AI endpoint is accessed, it can set an HTTP-only, SameSite=Lax cookie named toolsapp_ai_session, scoped to /api/ai, for up to 30 days.", "That random identifier groups a soft per-process generation allowance. It is not an account, advertising identifier, or durable entitlement. See Cookie & Data Handling for a complete current inventory."] },
  { id: "third-parties", title: "7. Third-party services", paragraphs: ["OpenAI is the optional AI provider when a server API key is configured. GitHub is reached only when you choose an external repository or issue link. No payment, cloud-file-storage, advertising, or analytics provider is integrated in the current application."] },
  { id: "retention", title: "8. Retention, control, and security", paragraphs: ["Browser-local data follows your browser's retention behavior. The anonymous AI allowance is held in server process memory and can disappear on restart; the session cookie can remain until expiry or deletion.", "Reasonable validation and data-minimization controls are implemented, but no internet or local software system can guarantee absolute security. Keep your browser and device secure and review generated outputs before use."] },
  { id: "contact", title: "9. Questions and updates", paragraphs: ["Use the Support page for current help and the linked public GitHub issue channel for privacy questions or corrections. Do not place private information in a public issue.", "This policy may change as real account, payment, analytics, or hosting integrations are added. Material implementation changes should be reflected here before they are represented as available."] },
];

const termsSections: readonly LegalSection[] = [
  { id: "acceptance", title: "1. Using the service", paragraphs: ["By using ToolsApp, you agree to use the service lawfully and responsibly. If you do not agree with these terms, do not use the service.", "The current service is an evolving software project provided under temporary naming. These terms do not identify or create a separate company, registered office, or governing jurisdiction."] },
  { id: "responsibilities", title: "2. Your responsibilities", paragraphs: ["You are responsible for the files, text, prompts, URLs, and other inputs you choose to process and for ensuring that you have the necessary rights and permissions."], bullets: ["Do not use the service to violate law, privacy, intellectual-property, or contractual rights.", "Do not attempt to compromise the service, evade safeguards, distribute malware, or interfere with other users.", "Do not submit credentials, secrets, or highly sensitive information unless a feature explicitly supports and protects it."] },
  { id: "outputs", title: "3. Tool output limitations", paragraphs: ["Outputs can be incomplete, lossy, inaccurate, or unsuitable for a particular purpose. File conversion may change quality or layout. Calculator results depend on your inputs and configured scales.", "Always inspect outputs and retain original files. ToolsApp does not provide professional legal, medical, financial, tax, or academic advice or guarantee a particular outcome."] },
  { id: "ai-content", title: "4. AI-generated content", paragraphs: ["AI output can contain errors, omissions, or inappropriate suggestions. You must verify product claims, rights, disclosures, platform rules, and factual accuracy before publishing or relying on generated material.", "The UGC workflow instructs the provider not to invent claims or verified testimonials, but this instruction is not a guarantee. Provider refusals and availability limits can prevent generation."] },
  { id: "files", title: "5. File processing", paragraphs: ["Browser-based processing depends on device memory, browser capabilities, supported formats, and stated limits. ToolsApp does not guarantee recovery of unsaved work or exact preservation of source formatting."] },
  { id: "accounts-billing", title: "6. Accounts and billing", paragraphs: ["Persistent production accounts and paid subscriptions are not currently enabled. Free is the only active plan; Pro is a planned direction, not a purchasable entitlement.", "If account or payment features are introduced, applicable terms, prices, renewals, cancellation controls, and provider details must be presented before a transaction occurs."] },
  { id: "ip", title: "7. Intellectual property", paragraphs: ["You retain responsibility for and rights in your lawful inputs. Subject to third-party rights and applicable law, you may use outputs created from those inputs. The ToolsApp interface, source, and supporting materials remain subject to their applicable ownership and license terms."] },
  { id: "availability", title: "8. Availability and third parties", paragraphs: ["The service may change, experience errors, or become unavailable without guarantee. Optional AI generation depends on OpenAI configuration and availability; external GitHub links are governed by GitHub's terms."] },
  { id: "disclaimers", title: "9. Disclaimers and reasonable limits", paragraphs: ["To the extent permitted by applicable law, the service is provided as available and without warranties of uninterrupted operation, fitness for a particular purpose, or error-free output.", "Nothing in these terms excludes rights or liabilities that cannot lawfully be excluded. Because no legal entity or jurisdiction has been specified, obtain qualified advice before relying on these terms for a commercial launch."] },
  { id: "changes", title: "10. Changes and contact", paragraphs: ["These terms may be updated as the implementation changes. The updated date on this page indicates the current version.", "Use the Support page and its public GitHub issue channel for questions or corrections, but do not post confidential information publicly."] },
];

const cookieSections: readonly LegalSection[] = [
  { id: "current-use", title: "Current technology inventory", paragraphs: ["ToolsApp does not currently use advertising, behavioral targeting, analytics, or payment cookies. A large consent banner is therefore not shown."] },
  { id: "ai-cookie", title: "AI allowance cookie", paragraphs: ["Accessing the AI usage endpoint can set toolsapp_ai_session: a random UUID stored in an HTTP-only, SameSite=Lax cookie, scoped to /api/ai, with a maximum age of 30 days.", "The server uses it only to group the current soft daily AI allowance. The cookie cannot be read by client-side JavaScript, does not identify an account, and may outlive the process-memory counter it refers to."] },
  { id: "local-storage", title: "Local storage", paragraphs: ["Local storage is not a cookie, but it persists data in your browser. ToolsApp uses versioned local-storage records for favorites, tool history, recent searches, notification state, and local Settings preferences.", "These records are functional product storage, not cross-site tracking. You can clear favorites and history in Settings and remove all site data through browser controls."] },
  { id: "memory", title: "Session and in-memory data", paragraphs: ["Tool inputs and results are commonly held in page memory while you work. They may disappear on refresh or when the tab closes. Temporary object URLs support downloads and are revoked by the application after use."] },
  { id: "control", title: "Your controls", paragraphs: ["You can block or remove cookies and storage through browser settings, although doing so can reset favorites, history, preferences, and the soft AI allowance identifier.", "If analytics, payments, or other non-essential tracking are added later, this inventory and any required consent controls must be updated before those technologies are represented as active."] },
];

const config = {
  privacy: { eyebrow: "PRIVACY", title: "Privacy Policy", description: "A conservative account of what stays in your browser, what reaches the server, and when a configured AI provider processes content.", icon: ShieldCheck, sections: privacySections },
  terms: { eyebrow: "TERMS", title: "Terms of Service", description: "Ground rules and limitations for using the current ToolsApp implementation responsibly.", icon: Scale, sections: termsSections },
  cookies: { eyebrow: "DATA HANDLING", title: "Cookie & Data Handling", description: "The complete current inventory of cookies, local storage, and temporary browser data.", icon: Cookie, sections: cookieSections },
} as const;

export function LegalExperience({ kind }: { kind: LegalKind }) {
  const page = config[kind];
  const Icon = page.icon;
  return (
    <main className={styles.page} id="main-content">
      <header className={styles.legalHero}><span className={styles.heroIcon}><Icon aria-hidden="true" size={22} /></span><span className={styles.eyebrow}>{page.eyebrow}</span><h1 className="font-heading">{page.title}</h1><p>{page.description}</p><time dateTime="2026-09-21">Updated September 21, 2026</time></header>
      <div className={styles.legalLayout}>
        <aside><strong>On this page</strong><nav>{page.sections.map((section) => <a href={`#${section.id}`} key={section.id}>{section.title.replace(/^\d+\.\s*/, "")}</a>)}</nav><div><FileText aria-hidden="true" size={18} /><p>Implementation-focused information, not legal advice.</p></div></aside>
        <article className={styles.legalArticle}>{page.sections.map((section) => <section id={section.id} key={section.id}><h2 className="font-heading">{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.bullets ? <ul>{section.bullets.map((item) => <li key={item}>{item}</li>)}</ul> : null}</section>)}</article>
      </div>
      <nav aria-label="Legal pages" className={styles.legalLinks}><Link aria-current={kind === "privacy" ? "page" : undefined} href="/privacy">Privacy</Link><Link aria-current={kind === "terms" ? "page" : undefined} href="/terms">Terms</Link><Link aria-current={kind === "cookies" ? "page" : undefined} href="/cookies">Cookies & data</Link><Link href="/support">Support</Link></nav>
      <DiscoveryFooter />
    </main>
  );
}
